### ISSUE TITLE
This plugin could break autocmd FileType sml

### ISSUE THREAD

**Issue by Huxpro** [jez/vim-better-sml#13]
For unknown reasons...the `au FileType sml` key mapping only get registered (checked via `:map`) when this plugin is removed.

Haven't got time investigating more.

**Comment by Huxpro** [comment]
Okay I figured out the reason (-ish)
I was following the `README` and write `augroup vimbettersml` in `vimrc`
while `augroup vimbettersml` has been declared in <https://github.com/jez/vim-better-sml/blob/master/ftplugin/sml.vim#L23> 

After changing the `augroup` as another name the autocmd group activates fine ;)

**Comment by jez** [comment]
Fixed in #14
