### ISSUE TITLE
Weird REPL output

### ISSUE THREAD

**Issue by danielfalbo** [jez/vim-better-sml#16]
![Screenshot 2020-08-04 at 11 45 43](https://user-images.githubusercontent.com/39460524/89279835-2251d880-d648-11ea-9d44-55d9f0eff8f8.png)
Hi !  When I open the repl, the output is weird: does not go to the next line when it should and puts some tabs when it shouldn't, does anyone know how to fix this? If I add semicolons to the source code everything is fine except it does not show me the hidden values anymore : (
![Screenshot 2020-08-04 at 11 49 59](https://user-images.githubusercontent.com/39460524/89280245-a2783e00-d648-11ea-9cac-d5109484dc03.png)
Thanks in advance : )

**Comment by danielfalbo** [comment]
This is the Health report: 
![Screenshot 2020-08-04 at 11 50 50](https://user-images.githubusercontent.com/39460524/89280329-c3d92a00-d648-11ea-9d48-1dd7291a59fa.png)

**Comment by k4rtik** [comment]
What version of SML/NJ are you on? The latest 110.98 has a bug and if you use homebrew for installation, see this post: https://github.com/Homebrew/homebrew-cask/pull/86821#issuecomment-666507292

**Comment by danielfalbo** [comment]
Thank you much! Solved it : )
